# Meta Data for SEO

## Homepage
title = "Hugo Newbie"
titleSeparator = "-"
titleAddition = "Sharing the joys, challenges, annoyances and successes of learning to build websites with Hugo"
description = "Hugo is awesome. But it's not without its learning curve. This site is documenting one woman's experience with the curve."

## Open Graph + Twitter Cards
images = ["hugonewbie.png"]
twitterSite = "mroswell"
twitterCreator = "mroswell"
facebookAuthor = "marjorie.roswell"
facebookPublisher = "marjorie.roswell"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "hugonewbie.png"
schemaTwitter = "https://twitter.com/mroswell"
schemaLinkedIn = "https://www.linkedin.com/in/marjorie-roswell/"
schemaGitHub = "https://github.com/mroswell"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
